### PR TITLE
Revamped README

### PR DESCRIPTION
**Pull request by TheEvilSkeleton**
Hello, I have found a lot of issues when reading your README, so I have decided to fix it and make it a bit prettier. Enjoy.

- Fixed typos and grammars
- Categorised instructions
- Added Table of contents
- Added more precision in some stuff

You should also change the description of the repository to:
`GOverlay is an open source project aimed to create a Graphical UI to manage Linux overlays.`

### CODE REVIEW

**Comment by benjamimgois** [comment]
Hey @TheEvilSkeleton thankyou very much for this changes. They are indeed much better. I'll merge it right now.

**Comment by TheEvilSkeleton** [comment]
No problem ^^

**Comment by TheEvilSkeleton** [comment]
@benjamimgois also forgot to mention, I also made created an issue in the MangoHud repository, here: https://github.com/flightlessmango/MangoHud/issues/115

**Comment by benjamimgois** [comment]
Thanks for the help man ! Actually the heavy leafting is done by MangoHud, i'm just trying to make it easier to everyone use. Be my guest to any other suggestions.

**Comment by resynth1943** [comment]
Looks good, @TheEvilSkeleton. Thank you for your contribution. :heart:

**Pull request merged**
