### PR TITLE
Default to Qt5

### PR DESCRIPTION
**Pull request by stephanlachnit**
This defaults to Qt5 within Lazarus and removes the local session files from git.

tl;dr: no need for `--ws=qt5` anymore. I also removed the `*.lps` session file from this repo as it really is a local file which contains no build information.

### CODE REVIEW

**Comment by stephanlachnit** [comment]
@benjamimgois can you do a 0.4.2 with this release? Then I publish it for my talk tmw, I don't think 0.4.1 is possible due to the tarball in the source.

**Comment by benjamimgois** [comment]
Thanks @stephanlachnit ! Nice work

**Comment by benjamimgois** [comment]
Ops... i just merge the code. But will change it to 0.4.2

**Comment by benjamimgois** [comment]
@stephanlachnit i just uploaded the 0.4.2 tag. Will make binary release for 0.4.2

**Pull request merged**
