### PR TITLE
ReplaySorcery consistent naming

### PR DESCRIPTION
**Pull request by stephanlachnit**
ReplaySorcery calls itself "ReplaySorcery" and not "Replay-Sorcery" or "Replay Sorcery", so I made the naming more consistent.

### CODE REVIEW

**Comment by benjamimgois** [comment]
Thanks man ! nice work as always !

**Comment by benjamimgois** [comment]
Ops... @stephanlachnit just now i noticed i forgot to click on the merge button. Sorry dude, my mistake... Now it says there's a conflict with overlayunit.lfm

**Comment by stephanlachnit** [comment]
Will try to resolve this weekend.

**Comment by stephanlachnit** [comment]
Resolved

**Pull request merged**
