### PR TITLE
FIX: Update dependencies definition to QT6

### LINKED ISSUE #103: Is Goverlay 1.1 supposed to be qt6 compatible?
Hi,

Congrats on the new [1.1 release](https://github.com/benjamimgois/goverlay/releases/tag/1.1).
I'm a bit confused by the release note though, the wording in there does not make it clear if Goverlay is qt6 compatible yet or if this is still an ongoing effort.

For instance: 
> "Plasma 6 is on the horizon, and we're eager to ride that wave by updating goverlay to QT6 **ASAP** [...]". 

The "ASAP" mention here seems to imply that this is an ongoing effort, but the release note later says:

> "New: We've given our toolkit a snazzy upgrade to QT6."

The fact that [these commits](https://github.com/benjamimgois/goverlay/compare/1.1...main) have been pushed **after** the 1.1 release gives me doubts on the above as well.

The reason I'm asking you this is because Goverlay 1.1 fails to build against qt6(pas) and, regarding the above, I'm not sure if is this expected (as in "Goverlay 1.1 still expects to be build against qt5(pas)") or if this is an actual issue.

If it's the latter, I found that there are some hard-coded leftover mentions of QT5 in the dependencies' definition, causing the build to fail against QT6. I opened https://github.com/benjamimgois/goverlay/pull/104 with a fix.

### PR DESCRIPTION
**Pull request by Antiz96**
Hi,

As said in https://github.com/benjamimgois/goverlay/issues/103, I'm not sure if Goverlay 1.1 is supposed to be qt6(pas) compatible yet or not but, if it is, building it against qt6 currently fails with the following error:

```
/usr/bin/ld: cannot find -lQt5Pas: No such file or directory
/build/goverlay/src/goverlay-1.1/goverlay.lpr(23,1) Error: (9013) Error while linking
/build/goverlay/src/goverlay-1.1/goverlay.lpr(23,1) Fatal: (10026) There were 1 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode
Error: (lazarus) Compile Project, Mode: Release, Target: /build/goverlay/src/goverlay-1.1/goverlay: stopped with exit code 1
Error: (lazbuild) failed compiling of project /build/goverlay/src/goverlay-1.1/goverlay.lpi
make: *** [Makefile:9: goverlay] Error 2
```

This is because there are still some hard-coded mentions of qt5 in dependencies definition causing the build to fail against qt6(pas). This pull request aims to update every leftover mentions of qt5 to qt6 in order to prevent the build against qt6 to fail.

Fixes https://github.com/benjamimgois/goverlay/issues/103

### CODE REVIEW

**Comment by benjamimgois** [comment]
@Antiz96 indeed there were still hardcode mentions to qt5 in the sourcecode. I didn't realize that i still have qt5pas installed on my system and even using Lazarus-QT6 with qt6pas i was still generating qt5 interface. With your fix, it seems to be working as it should now. I'll just push a update with your modifications, thankyou very much !

**Comment by Antiz96** [comment]
@benjamimgois Cool, thanks a lot for the confirmation and for your actions!

**Comment by Antiz96** [comment]
@benjamimgois Thanks for the new release! Just to make sure, did you intend to release it as 1.10 (instead of 1.1.1 or 1.2)?

**Comment by benjamimgois** [comment]
Yeah, i though that 1.1.1 would be a strange number and 1.2 shoud have more improvements. I'll keep as 1.10 by the moment.

**Comment by Antiz96** [comment]
Well... That's not so standard but okay. However, that means that the next release should be higher than 1.10 (so 1.10.1 or 1.11). Going back to something like 1.2 would be seen as inferior as 1.10 which will be a problem for linux distributions packaging Goverlay (as their respective package manager will not interpret 1.2 as a higher version than 1.10).

**Comment by Antiz96** [comment]
For reference: https://semver.org/#spec-item-11

**Comment by Antiz96** [comment]
> Well... That's not so standard but okay. However, that means that the next release should be higher than 1.10 (so 1.10.1 or 1.11). Going back to something like 1.2 would be seen as inferior as 1.10 which will be a problem for linux distributions packaging Goverlay (as their respective package manager will not interpret 1.2 as a higher version than 1.10).

@benjamimgois I'm really sorry to insist but it would be great to have a confirmation that you're aware of the above and that you're fine with it before I push Goverlay 1.10 to Arch Linux repositories. 
Having the next release getting a tag that would be seen as inferior as 1.10 would require additional and manual burdens for packagers to avoid an unexpected behavior (namely having distribution's package managers not seeing/accepting the new release as a higher version than version 1.10, preventing users to get the update as expected). And that is for all linux distributions packaging Goverlay (not only Arch).

**Comment by benjamimgois** [comment]
Ouch, i didn't knew it would become a problem with package managers. In that case i'll rename it to 1.1.1.  Thanks for the alert !

**Comment by Antiz96** [comment]
> Ouch, i didn't knew it would become a problem with package managers. In that case i'll rename it to 1.1.1.  Thanks for the alert !

Thanks a lot for your understanding! 😊

**Comment by Bitwolfies** [comment]
FYI, does not seem like the issue is fixed on arch, the packaged 1.1.1-1 still fails to launch with "goverlay: symbol lookup error: /usr/lib/libQt6Pas.so.6: undefined symbol: _ZNK7QString12isSimpleTextEv, version Qt_"

**Pull request merged**
